name: Maven Check Style

on:
  push:
    branches:
      - main

jobs:
  maven-check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.16.1
      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar

      - name: Run Checkstyle
        run: java -jar checkstyle-8.44-all.jar -c config/Checkstyle.xml src/
