name: Maven Check Style

on:
  push:
    branches:
      - main

jobs:
  maven-check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Download Checkstyle
        run: wget https://checkstyle.org/dtds/configuration_1_3.dtd

      - name: Run Checkstyle
        run: java -jar configuration_1_3.dtd -c config/Checkstyle.xml src/
