name: Maven Check Style

on:
  push:
    branches:
      - main

jobs:
  maven-check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.15.0/checkstyle-10.15.0-all.jar

      - name: Run Checkstyle
        run: java -jar checkstyle-10.15.0-all.jar
